name: This is my first workflow
on:
    push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: List all environment variables
          run: env
          
        - name: List files in workspace
          run: ls $GITHUB_WORKSPACE
        - name: welcome message
          run: echo "Hello , this is first workflow"

        - name: list files
          run: ls

        - name: read files
          run: cat README.md
          
