name: This is my first workflow
on:
    push

jobs:
    first_job:
        runs-on: ubuntu_latest
        steps:
        - name: welcome message
          run: echo "Hello , this is first workflow"

        - name: list files
          run: ls

        - name: read files
          run: cat README.md
          
