name: multijobs----

on:
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

    - name: uploading the artifact
      uses: actions/upload-artifact@v4
      with:
        name: my_dragon.txt
        path: dragon.txt

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
    - name: checking files seconds
      run:  ls -ltr

    - name: uploading the artifact
      uses: actions/download-artifact@v4
      with:
        name: my_dragon.txt

    - name: checking files after download 
      run:  ls -ltr
    

    - name: Test File Exists
      run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    needs: [test_job_2,build_job_1]
    steps:

    - name: checking files seconds
      run:  ls -ltr
  
    - name: uploading the artifact
      uses: actions/download-artifact@v4
      with:
        name: my_dragon.txt
  
    - name: checking files after download 
      run:  ls -ltr
    
    - name: Read File
      run: cat dragon.txt
